name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'challenge-series/ocp-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_JSON }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./challenge-series/ocp-service
          file: ./challenge-series/ocp-service/Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/neilprimmer/challenge-series/ocp-service:latest
