name: 'Infrastructure via Terraform'

on:
  push:
    branches:
      - main

env:
  GITHUB_USERNAME: ${{github.repository_owner}}
  CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_ACCESS_TOKEN}}
  CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
  CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
  GOOGLE_CREDENTIALS: ${{secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_JSON}}

jobs:
  terraform:
    name: "Deploy Challenge Series Infrastructure"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup TF
        uses: hashicorp/setup-terraform@v1
      - name: Initialize TF
        run: terraform init
        working-directory: "terraform/"
      - name: Terraform Plan
        run: terraform plan -out ${{github.sha}}.tfplan -var="cloudflare_api_token=${CLOUDFLARE_TOKEN}" -var="cloudflare_zone_id=${CLOUDFLARE_ZONE_ID}" -var="cloudflare_account_id=${CLOUDFLARE_ACCOUNT_ID}""
        working-directory: "terraform/"
      - name: Terraform Apply
        run: terraform apply ${{github.sha}}.tfplan
        working-directory: "terraform/"
